services:
  app:
    build: .
    ports:
      - "5433:8080"
    depends_on:
      - shrimp_db
    networks:
      - custom_net
  shrimp_db:
    image: postgres:15-alpine
    container_name: shrimp_db
    environment:
      - POSTGRES_USER=shrimp_user
      - POSTGRES_PASSWORD=shrimp_password
      - POSTGRES_DB=shrimp_db
    restart: unless-stopped
    ports:
      - "5432:5432"
    networks:
      - custom_net

networks:
  custom_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16