// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.0
// source: crypto.proto

package rpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateRandomBytesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	N             uint32                 `protobuf:"varint,1,opt,name=n,proto3" json:"n,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRandomBytesRequest) Reset() {
	*x = GenerateRandomBytesRequest{}
	mi := &file_crypto_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRandomBytesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRandomBytesRequest) ProtoMessage() {}

func (x *GenerateRandomBytesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRandomBytesRequest.ProtoReflect.Descriptor instead.
func (*GenerateRandomBytesRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateRandomBytesRequest) GetN() uint32 {
	if x != nil {
		return x.N
	}
	return 0
}

type GenerateRandomBytesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []byte                 `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRandomBytesResponse) Reset() {
	*x = GenerateRandomBytesResponse{}
	mi := &file_crypto_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRandomBytesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRandomBytesResponse) ProtoMessage() {}

func (x *GenerateRandomBytesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRandomBytesResponse.ProtoReflect.Descriptor instead.
func (*GenerateRandomBytesResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateRandomBytesResponse) GetData() []byte {
	if x != nil {
		return x.Data
	}
	return nil
}

type DeriveKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Password      string                 `protobuf:"bytes,1,opt,name=password,proto3" json:"password,omitempty"`
	Salt          []byte                 `protobuf:"bytes,2,opt,name=salt,proto3" json:"salt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveKeyRequest) Reset() {
	*x = DeriveKeyRequest{}
	mi := &file_crypto_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveKeyRequest) ProtoMessage() {}

func (x *DeriveKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveKeyRequest.ProtoReflect.Descriptor instead.
func (*DeriveKeyRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{2}
}

func (x *DeriveKeyRequest) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *DeriveKeyRequest) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

type DeriveKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeriveKeyResponse) Reset() {
	*x = DeriveKeyResponse{}
	mi := &file_crypto_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeriveKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeriveKeyResponse) ProtoMessage() {}

func (x *DeriveKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeriveKeyResponse.ProtoReflect.Descriptor instead.
func (*DeriveKeyResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{3}
}

func (x *DeriveKeyResponse) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

type EncryptWithKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Plaintext     []byte                 `protobuf:"bytes,2,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptWithKeyRequest) Reset() {
	*x = EncryptWithKeyRequest{}
	mi := &file_crypto_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptWithKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptWithKeyRequest) ProtoMessage() {}

func (x *EncryptWithKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptWithKeyRequest.ProtoReflect.Descriptor instead.
func (*EncryptWithKeyRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{4}
}

func (x *EncryptWithKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *EncryptWithKeyRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type EncryptWithKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Salt          []byte                 `protobuf:"bytes,1,opt,name=salt,proto3" json:"salt,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptWithKeyResponse) Reset() {
	*x = EncryptWithKeyResponse{}
	mi := &file_crypto_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptWithKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptWithKeyResponse) ProtoMessage() {}

func (x *EncryptWithKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptWithKeyResponse.ProtoReflect.Descriptor instead.
func (*EncryptWithKeyResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{5}
}

func (x *EncryptWithKeyResponse) GetSalt() []byte {
	if x != nil {
		return x.Salt
	}
	return nil
}

func (x *EncryptWithKeyResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *EncryptWithKeyResponse) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DecryptWithKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           []byte                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,2,opt,name=nonce,proto3" json:"nonce,omitempty"`
	Ciphertext    []byte                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptWithKeyRequest) Reset() {
	*x = DecryptWithKeyRequest{}
	mi := &file_crypto_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptWithKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptWithKeyRequest) ProtoMessage() {}

func (x *DecryptWithKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptWithKeyRequest.ProtoReflect.Descriptor instead.
func (*DecryptWithKeyRequest) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{6}
}

func (x *DecryptWithKeyRequest) GetKey() []byte {
	if x != nil {
		return x.Key
	}
	return nil
}

func (x *DecryptWithKeyRequest) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *DecryptWithKeyRequest) GetCiphertext() []byte {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

type DecryptWithKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptWithKeyResponse) Reset() {
	*x = DecryptWithKeyResponse{}
	mi := &file_crypto_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptWithKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptWithKeyResponse) ProtoMessage() {}

func (x *DecryptWithKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_crypto_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptWithKeyResponse.ProtoReflect.Descriptor instead.
func (*DecryptWithKeyResponse) Descriptor() ([]byte, []int) {
	return file_crypto_proto_rawDescGZIP(), []int{7}
}

func (x *DecryptWithKeyResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

var File_crypto_proto protoreflect.FileDescriptor

const file_crypto_proto_rawDesc = "" +
	"\n" +
	"\fcrypto.proto\x12\tcrypto.v1\"*\n" +
	"\x1aGenerateRandomBytesRequest\x12\f\n" +
	"\x01n\x18\x01 \x01(\rR\x01n\"1\n" +
	"\x1bGenerateRandomBytesResponse\x12\x12\n" +
	"\x04data\x18\x01 \x01(\fR\x04data\"B\n" +
	"\x10DeriveKeyRequest\x12\x1a\n" +
	"\bpassword\x18\x01 \x01(\tR\bpassword\x12\x12\n" +
	"\x04salt\x18\x02 \x01(\fR\x04salt\"%\n" +
	"\x11DeriveKeyResponse\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\"G\n" +
	"\x15EncryptWithKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x1c\n" +
	"\tplaintext\x18\x02 \x01(\fR\tplaintext\"b\n" +
	"\x16EncryptWithKeyResponse\x12\x12\n" +
	"\x04salt\x18\x01 \x01(\fR\x04salt\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\"_\n" +
	"\x15DecryptWithKeyRequest\x12\x10\n" +
	"\x03key\x18\x01 \x01(\fR\x03key\x12\x14\n" +
	"\x05nonce\x18\x02 \x01(\fR\x05nonce\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\fR\n" +
	"ciphertext\"6\n" +
	"\x16DecryptWithKeyResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext2\xeb\x02\n" +
	"\rCryptoService\x12d\n" +
	"\x13GenerateRandomBytes\x12%.crypto.v1.GenerateRandomBytesRequest\x1a&.crypto.v1.GenerateRandomBytesResponse\x12F\n" +
	"\tDeriveKey\x12\x1b.crypto.v1.DeriveKeyRequest\x1a\x1c.crypto.v1.DeriveKeyResponse\x12U\n" +
	"\x0eEncryptWithKey\x12 .crypto.v1.EncryptWithKeyRequest\x1a!.crypto.v1.EncryptWithKeyResponse\x12U\n" +
	"\x0eDecryptWithKey\x12 .crypto.v1.DecryptWithKeyRequest\x1a!.crypto.v1.DecryptWithKeyResponseB1Z/github.com/Krev3tka/ShrimPG/internal/crypto/rpcb\x06proto3"

var (
	file_crypto_proto_rawDescOnce sync.Once
	file_crypto_proto_rawDescData []byte
)

func file_crypto_proto_rawDescGZIP() []byte {
	file_crypto_proto_rawDescOnce.Do(func() {
		file_crypto_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)))
	})
	return file_crypto_proto_rawDescData
}

var file_crypto_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_crypto_proto_goTypes = []any{
	(*GenerateRandomBytesRequest)(nil),  // 0: crypto.v1.GenerateRandomBytesRequest
	(*GenerateRandomBytesResponse)(nil), // 1: crypto.v1.GenerateRandomBytesResponse
	(*DeriveKeyRequest)(nil),            // 2: crypto.v1.DeriveKeyRequest
	(*DeriveKeyResponse)(nil),           // 3: crypto.v1.DeriveKeyResponse
	(*EncryptWithKeyRequest)(nil),       // 4: crypto.v1.EncryptWithKeyRequest
	(*EncryptWithKeyResponse)(nil),      // 5: crypto.v1.EncryptWithKeyResponse
	(*DecryptWithKeyRequest)(nil),       // 6: crypto.v1.DecryptWithKeyRequest
	(*DecryptWithKeyResponse)(nil),      // 7: crypto.v1.DecryptWithKeyResponse
}
var file_crypto_proto_depIdxs = []int32{
	0, // 0: crypto.v1.CryptoService.GenerateRandomBytes:input_type -> crypto.v1.GenerateRandomBytesRequest
	2, // 1: crypto.v1.CryptoService.DeriveKey:input_type -> crypto.v1.DeriveKeyRequest
	4, // 2: crypto.v1.CryptoService.EncryptWithKey:input_type -> crypto.v1.EncryptWithKeyRequest
	6, // 3: crypto.v1.CryptoService.DecryptWithKey:input_type -> crypto.v1.DecryptWithKeyRequest
	1, // 4: crypto.v1.CryptoService.GenerateRandomBytes:output_type -> crypto.v1.GenerateRandomBytesResponse
	3, // 5: crypto.v1.CryptoService.DeriveKey:output_type -> crypto.v1.DeriveKeyResponse
	5, // 6: crypto.v1.CryptoService.EncryptWithKey:output_type -> crypto.v1.EncryptWithKeyResponse
	7, // 7: crypto.v1.CryptoService.DecryptWithKey:output_type -> crypto.v1.DecryptWithKeyResponse
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_crypto_proto_init() }
func file_crypto_proto_init() {
	if File_crypto_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_crypto_proto_rawDesc), len(file_crypto_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_crypto_proto_goTypes,
		DependencyIndexes: file_crypto_proto_depIdxs,
		MessageInfos:      file_crypto_proto_msgTypes,
	}.Build()
	File_crypto_proto = out.File
	file_crypto_proto_goTypes = nil
	file_crypto_proto_depIdxs = nil
}
